<?php

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_59243a26d17fa',
	'title' => 'SEO',
	'fields' => array (
		array (
			'key' => 'field_59243a2c6382e',
			'label' => 'Facebook Share Image',
			'name' => 'fb_share_image',
			'type' => 'image',
			'instructions' => 'This image will be used when someone shares a link to the site via Facebook. The image must be exactly 1200 x 630 pixels according to Facebook guidelines. You can preview how the image will look via <a href="https://developers.facebook.com/tools/debug/" target="_blank">this tool</a> from Facebook. If you upload a new image and the tool still displays the old one, find the "Scrape Again" button, and the new one should load.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'id',
			'preview_size' => 'medium_large',
			'library' => 'all',
			'min_width' => 1200,
			'min_height' => 630,
			'min_size' => '',
			'max_width' => 1200,
			'max_height' => 630,
			'max_size' => '',
			'mime_types' => 'jpg, png',
		),
		array (
			'key' => 'field_59243b2f6382f',
			'label' => 'Twitter Share Image',
			'name' => 'twitter_share_image',
			'type' => 'image',
			'instructions' => 'This image will be used when someone shares a link to the site via Twitter. The image must be exactly 1024 x 512 pixels according to Twitter guidelines. You can preview how the image will look via <a href="https://cards-dev.twitter.com/validator" target="_blank">this tool</a> from Twitter.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'id',
			'preview_size' => 'medium_large',
			'library' => 'all',
			'min_width' => 1024,
			'min_height' => 512,
			'min_size' => '',
			'max_width' => 1024,
			'max_height' => 512,
			'max_size' => '',
			'mime_types' => 'jpg, png',
		),
		array (
			'key' => 'field_59243c9863830',
			'label' => 'Share Card Title',
			'name' => 'share_title',
			'type' => 'text',
			'instructions' => 'In addition to the images uploaded above, Facebook, Twitter, and other social media sites will also add some text to the share card. The text consists of a title and subtitle. You can customize the title text here.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_59243e4363831',
			'label' => 'Share Card Subtitle',
			'name' => 'share_subtitle',
			'type' => 'text',
			'instructions' => 'You can customize the subtitle text for the share card here.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'seo',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;
